In [1]:
import scipy.io as sio
import os
import numpy as np
import tensorflow as tf
datapath = r'../data'
dataset = 'INSECT'
x = sio.loadmat(os.path.join(datapath, dataset, 'res101.mat'))
x2 = sio.loadmat(os.path.join(datapath, dataset, 'att_splits.mat')) 
barcodes=x['nucleotides_aligned'].T
species=x['labels']
train_loc=x2['trainval_loc']

2022-10-15 19:02:04.323205: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-15 19:02:04.534947: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-10-15 19:02:05.159625: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2022-10-15 19:02:05.159679: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or 

In [2]:
# Number of training samples and entire data
N = len(barcodes)
print(len(train_loc[0]), N)

15242 21212


In [3]:
# Reading barcodes and labels into python list
bcodes=[]
labels=[]
for i in range(N):
    if len(barcodes[i][0][0])>0:
        bcodes.append(barcodes[i][0][0])
        labels.append(species[i][0])
    

In [4]:
print('Sample barcode: %s' % bcodes[7])

Sample barcode: AACATTATACTTTATTTTTGGTGCATGATCAGGAATAGTCGGAACCTCTTTAAGAATGTTAATTCGACTTGAATTAGGAAACCCTGGGTCACTAATTGGTGATGACCAAATTTATAATGTAATTGTTACTGCACATGCATTTGTAATAATTTTTTTTATAGTAATGCCTATTATAATTGGAGGTTTCGGAAACTGACTAGTTCCTTTAATACTAGGAGCTCCTGATATAGCATTCCCTCGAATAAATAACATGAGATTCTGACTGCTCCCCCCTTCTTTAACCCTTCTCCTTATAAGCAGCATAGTTGAGAGAGGAGCTGGCACAGGTTGAACAGTTTACCCACCACTTTCTTCTAATATTGCCCATAGAGGAGCCTCAGTTGACCTAGCTATTTTTAGTCTACATTTAGCTGGAATTTCTTCAATTTTAGGAGCTGTAAATTTTATTACTACAATTATCAATATACGATCTGTAGGAATAACTTTTGACCGAATACCTTTATTTGTCTGATCAGTAGGAATTACTGCTCTGTTACTATTACTATCATTACCTGTATTAGCTGGAGCAATCACAATACTTCTAACAGATCGAAATTTAAATACTTCATTTTTTGATCCTGCAGGAGGTGGAGATCCAATTTTATACCAACATTTATTT


In [5]:
from tensorflow.keras.preprocessing.text import Tokenizer

# Converting base pairs, ACTG, into numbers
tokenizer = Tokenizer(char_level=True)
tokenizer.fit_on_texts(bcodes)
sequence_of_int = tokenizer.texts_to_sequences(bcodes)

In [6]:
sequence_of_int[3]

[2,
 2,
 3,
 2,
 1,
 1,
 2,
 1,
 2,
 3,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 4,
 4,
 1,
 4,
 3,
 2,
 1,
 4,
 2,
 1,
 3,
 2,
 4,
 4,
 2,
 2,
 1,
 2,
 4,
 1,
 3,
 4,
 4,
 2,
 2,
 3,
 3,
 1,
 3,
 1,
 1,
 1,
 2,
 2,
 4,
 2,
 2,
 1,
 4,
 1,
 1,
 2,
 2,
 1,
 1,
 3,
 4,
 2,
 3,
 1,
 1,
 4,
 2,
 2,
 1,
 1,
 2,
 4,
 4,
 2,
 2,
 2,
 3,
 3,
 3,
 1,
 4,
 4,
 4,
 1,
 3,
 2,
 3,
 1,
 2,
 2,
 1,
 1,
 4,
 4,
 1,
 4,
 2,
 1,
 4,
 2,
 3,
 3,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 1,
 2,
 2,
 1,
 4,
 1,
 2,
 2,
 1,
 1,
 4,
 1,
 1,
 2,
 3,
 1,
 4,
 3,
 2,
 3,
 2,
 1,
 4,
 3,
 2,
 1,
 1,
 1,
 4,
 1,
 2,
 2,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 4,
 1,
 2,
 2,
 1,
 4,
 3,
 3,
 1,
 2,
 1,
 1,
 2,
 1,
 2,
 2,
 1,
 1,
 4,
 4,
 2,
 4,
 4,
 1,
 1,
 1,
 3,
 4,
 4,
 2,
 2,
 2,
 3,
 1,
 4,
 2,
 3,
 1,
 2,
 4,
 1,
 1,
 3,
 3,
 1,
 1,
 1,
 2,
 2,
 1,
 2,
 3,
 1,
 2,
 4,
 4,
 2,
 4,
 3,
 1,
 3,
 3,
 1,
 4,
 2,
 1,
 2,
 1,
 2,
 4,
 3,
 2,
 1,
 1,
 3,
 3,
 3,
 1,
 3,
 4,
 2,
 2,
 1,
 2,
 2,
 2,
 1,
 2,
 2,
 3,


In [7]:
# For INSECT dataset, majority of barcodes have a length of 658
cnt = 0
ll = np.zeros((N, 1))
for i in range(N):
    ll[i] = len(sequence_of_int[i])
    if ll[i]==658:
        #print(i)
        cnt += 1
print(cnt, np.median(ll))

19863 658.0


In [8]:
import numpy as np

# Calculating sequence count for each species
cl = len(np.unique(species))
seq_len=np.zeros((cl))
seq_cnt=np.zeros((cl))
for i in range(N):
    k=labels[i]-1  # Accounting for Matlab labeling
    seq_cnt[k]+=1
    #seq_len[k]+=len(sequence_of_int[k])
    
print('# classes: %d' % cl)

# classes: 1213


In [9]:
# Converting all the data into one-hot encoding. Note that this data is not used during training. 
# We are getting it ready for the prediction time to get the final DNA embeddings after training is done
sl = 658
allX=np.zeros((N,sl,5))
for i in range(N):
    Nt=len(sequence_of_int[i])

    for j in range(sl):
        if(len(sequence_of_int[i])>j):
            k=sequence_of_int[i][j]-1
            if(k>4):
                k=4
            allX[i][j][k]=1.0
            

In [10]:
# Initialize the training matrix and labels
trainX=np.zeros((N,sl,5))
trainY=np.zeros((N,cl))
labelY=np.zeros(N)

In [11]:
# Here is where we cap the class sample size to 50 for a balanced training set
Nc=-1
clas_cnt=np.zeros((cl))
for i in range(N):
    Nt=len(sequence_of_int[i])
    k=labels[i]-1
    clas_cnt[k]+=1
    itl=i+1
    if(seq_cnt[k]>=10 and clas_cnt[k]<=50 and itl in train_loc[0]): # Note that samples from training set are only used 
        Nc=Nc+1
        for j in range(sl):
            if(len(sequence_of_int[i])>j):
                k=sequence_of_int[i][j]-1
                if(k>4):
                    k=4
                trainX[Nc][j][k]=1.0
            
        k=labels[i]-1
        trainY[Nc][k]=1.0
        labelY[Nc]=k

In [12]:
print('Final training size: %d' % Nc)

Final training size: 14723


In [13]:
# selecting the balanced training set
trainX=trainX[0:Nc]
trainY=trainY[0:Nc]
labelY=labelY[0:Nc]
print(trainX.shape, trainY.shape, labelY.shape)

(14723, 658, 5) (14723, 1213) (14723,)


In [14]:
# To make sure the training data does not include any unseen class nucleotides
label_us = species[x2['test_unseen_loc'][0]-1]
np.intersect1d(np.unique(labelY), np.unique(label_us)-1)

array([], dtype=float64)

In [15]:
# Cleaning empty classes
idx = np.argwhere(np.all(trainY[..., :] == 0, axis=0))
trainY = np.delete(trainY, idx, axis=1)

print(len(idx), min(np.sum(trainY,axis=0)))

121 8.0


In [16]:
print(trainY.shape)
print(labelY.shape)

(14723, 1092)
(14723,)


In [17]:
# Expanding the training set shape for CNN 
trainX=np.expand_dims(trainX, axis=3)
allX=np.expand_dims(allX, axis=3)
print(trainX.shape)

(14723, 658, 5, 1)


In [18]:
from sklearn.model_selection import train_test_split

# Splitting the training set into train and validation
X_train, X_test, y_train, y_test = train_test_split(trainX, trainY, test_size=0.2, random_state=42)

In [19]:
print(X_train.shape)
print(X_train[0])

(11778, 658, 5, 1)
[[[0.]
  [1.]
  [0.]
  [0.]
  [0.]]

 [[0.]
  [1.]
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [1.]
  [0.]
  [0.]]

 ...

 [[1.]
  [0.]
  [0.]
  [0.]
  [0.]]

 [[1.]
  [0.]
  [0.]
  [0.]
  [0.]]

 [[1.]
  [0.]
  [0.]
  [0.]
  [0.]]]


### Classic CNN Model

In [20]:
from tensorflow.keras import datasets, layers, models, optimizers, callbacks

In [21]:
# CNN model architecture
model = models.Sequential()
model.add(layers.Conv2D(64, (3,3), activation='relu', input_shape=(sl, 5,1),padding="SAME"))
model.add(layers.BatchNormalization())
model.add(layers.MaxPooling2D((3,1)))
model.add(layers.Conv2D(32, (3,3), activation='relu',padding="SAME"))
model.add(layers.BatchNormalization())
model.add(layers.MaxPooling2D((3,1)))
model.add(layers.Conv2D(16, (3,3), activation='relu',padding="SAME"))
model.add(layers.BatchNormalization())
model.add(layers.MaxPooling2D((3,1)))
# model.add(layers.Conv2D(16, (3,3), activation='relu',padding="SAME"))
# model.add(layers.BatchNormalization())
# model.add(layers.MaxPooling2D((3,1)))
model.add(layers.Flatten())
model.add(layers.BatchNormalization())
model.add(layers.Dense(500, activation='tanh'))
model.add(layers.Dense(y_train.shape[1]))

2022-10-15 19:02:23.102944: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-15 19:02:23.126271: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory
2022-10-15 19:02:23.126289: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1934] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2022-10-15 19:02:23.126594: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN

In [22]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 658, 5, 64)        640       
                                                                 
 batch_normalization (BatchN  (None, 658, 5, 64)       256       
 ormalization)                                                   
                                                                 
 max_pooling2d (MaxPooling2D  (None, 219, 5, 64)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 219, 5, 32)        18464     
                                                                 
 batch_normalization_1 (Batc  (None, 219, 5, 32)       128       
 hNormalization)                                                 
                                                        

In [23]:
# Step-decay learning rate scheduler
def step_decay(epoch):
   initial_lrate = 0.001
   drop = 0.5
   epochs_drop = 2.0
   lrate = initial_lrate * np.power(drop, np.floor((1+epoch)/epochs_drop))
   return lrate

class LossHistory(callbacks.Callback):
    def on_train_begin(self, logs={}):
       self.losses = []
       self.lr = []
 
    def on_epoch_end(self, batch, logs={}):
       self.losses.append(logs.get('loss'))
       self.lr.append(step_decay(len(self.losses)))
        
loss_history = LossHistory()
lrate = callbacks.LearningRateScheduler(step_decay)
callbacks_list = [loss_history, lrate]

In [24]:
from tensorflow.keras.metrics import top_k_categorical_accuracy
#opt = tf.keras.optimizers.SGD(momentum=0.9, nesterov=True)
opt = tf.keras.optimizers.Adam()
model.compile(optimizer=opt, loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True),
              metrics=['accuracy','top_k_categorical_accuracy'])

# Validation time
history = model.fit(X_train, y_train, epochs=5, batch_size = 32, validation_data=(X_test, y_test), callbacks=callbacks_list, verbose=1)

# Final Test time
#history = model.fit(trainX, trainY, epochs=5, callbacks=callbacks_list)

Epoch 1/5
369/369 [==============================] - 44s 117ms/step - loss: 1.6481 - accuracy: 0.8087 - top_k_categorical_accuracy: 0.8577 - val_loss: 3.9617 - val_accuracy: 0.4727 - val_top_k_categorical_accuracy: 0.7565 - lr: 0.0010
Epoch 2/5
369/369 [==============================] - 29s 80ms/step - loss: 0.0617 - accuracy: 0.9941 - top_k_categorical_accuracy: 0.9998 - val_loss: 0.1047 - val_accuracy: 0.9885 - val_top_k_categorical_accuracy: 0.9963 - lr: 5.0000e-04
Epoch 3/5
369/369 [==============================] - 29s 80ms/step - loss: 0.0361 - accuracy: 0.9963 - top_k_categorical_accuracy: 1.0000 - val_loss: 0.0983 - val_accuracy: 0.9864 - val_top_k_categorical_accuracy: 0.9966 - lr: 5.0000e-04
Epoch 4/5
369/369 [==============================] - 30s 80ms/step - loss: 0.0215 - accuracy: 0.9968 - top_k_categorical_accuracy: 1.0000 - val_loss: 0.0770 - val_accuracy: 0.9878 - val_top_k_categorical_accuracy: 0.9966 - lr: 2.5000e-04
Epoch 5/5
369/369 [==============================] 

In [25]:
print('Learning rates through epochs:', loss_history.lr)

Learning rates through epochs: [0.0005, 0.0005, 0.00025, 0.00025, 0.000125]


In [26]:
from tensorflow.keras.models import Model

# Getting the DNA embeddings of all data from the last dense layer
layer_name = 'dense'
model2= Model(inputs=model.input, outputs=model.get_layer(layer_name).output)
dna_embeddings=model2.predict(allX)
print(dna_embeddings.shape)

663/663 [==============================] - 8s 13ms/step
(21212, 500)


In [27]:
# saving the results into csv file to be later read into matlab
np.savetxt("nips_cnn_embeddings_500_5e_adam_aligned.csv", dna_embeddings, delimiter=",")